[Visualizer] Remove plotly_visualizer from imports and README.md
Excess visualizers were removed with commit [e1286e6](https://github.com/jamzaon/ArHackathon2025/commit/e1286e6)

This fixes the following import error by removing these imports from __init__.py:

```
python scripts/visualize.py test_cases/level1/test_case_1.json

Traceback (most recent call last):
  File "/Volumes/workplace/ArHackathon2025/scripts/visualize.py", line 11, in <module>
    from ar_hackathon.simulation_runner import SimulationRunner
  File "/Volumes/workplace/ArHackathon2025/ar_hackathon/simulation_runner.py", line 13, in <module>
    from ar_hackathon.visualizers.base_visualizer import BaseVisualizer
  File "/Volumes/workplace/ArHackathon2025/ar_hackathon/visualizers/__init__.py", line 8, in <module>
    from ar_hackathon.visualizers.plotly_visualizer import PlotlyVisualizer
ModuleNotFoundError: No module named 'ar_hackathon.visualizers.plotly_visualizer'
```